nelmio_api_doc:
    documentation:
        info:
            title: BILEMO API
            description: REST API
            version: 1.0.0
        paths:
            /api/login_check:
                post:
                    tags:
                        - Token
                    operationId: postCredentialsItem
                    summary: Permet d'obtenir le token JWT pour se logger.
                    requestBody:
                        description: Créer un nouveau token JWT
                        content:
                            application/json:
                                schema:
                                    $ref: '#/components/schemas/Credentials'
                    responses:
                        '200':
                            description: Récupère le token JWT
                            content:
                                application/json:
                                    schema:
                                        $ref: '#/components/schemas/Token'
                        '400':
                            description: Invalid Credentials
                    security: []  # car le login est à accès public , pas sécurisé
        components:
            schemas:
                Token:
                    type: object
                    properties:
                        token:
                            type: string
                            readOnly: true
                Credentials:
                    type: object
                    properties:
                        username:
                            type: string
                            default: customer_3@testmail.fr
                        password:
                            type: string
                            default: password
            securitySchemes:
                Bearer:
                    type: http
                    scheme: bearer
                    bearerFormat: JWT
        security:
            - Bearer: []
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
            - ^/api/V1
        # host_patterns: # document only routes with a host of the form api.*
        #     - ^api\.
        disable_default_routes: true
