nelmio_api_doc:
    documentation:
        info:
            title: BILEMO API
            description: REST API
            version: 1.0.0
        components:
            securitySchemes:
                Bearer:
                    type: http
                    scheme: bearer
                    bearerFormat: JWT
        security:
            - Bearer: []
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
            - ^/api/V1
        # host_patterns: # document only routes with a host of the form api.*
        #     - ^api\.
        disable_default_routes: true
