controllersV1:
    resource: ../src/Controller/V1
    type: attribute
    prefix: /api/V1

controllersV2:
    resource: ../src/Controller/V2
    type: attribute
    prefix: /api/V2

kernel:
    resource: ../src/Kernel.php
    type: annotation

api_login_check:
    path: /api/login_check
    